services:
  qui:
    image: ghcr.io/hotio/qui
    container_name: qui
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "7476:7476"

    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - ~/volumes/qui/config:/config

networks:
  arr-stack:
    name: arr-stack
    external: true
