services:
  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "8989:8989"

    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - ~/volumes/sonarr/config:/config
      - ~/volumes/media:/media
