services:
  overseerr:
    image: ghcr.io/hotio/overseerr
    container_name: overseerr
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "5055:5055"

    volumes:
      - ~/volumes/overseerr/config:/config

    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

networks:
  arr-stack:
    name: arr-stack
    external: true
