services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "8080:8080"

    volumes:
      - ~/volumes/qbittorrent/config:/config
      - ./wg0.conf:/config/wireguard/wg0.conf:ro
      - ~/volumes/data/torrents:/torrents
      - ~/volumes/data:/data

    env_file: qbittorrent.env
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORTS=8080/tcp,8080/udp
      - LIBTORRENT=v1

    cap_add:
      - NET_ADMIN
