services:
  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    restart: unless-stopped

    networks:
      - arr-stack
    ports:
      - "7878:7878"

    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - ~/volumes/radarr/config:/config
      - ~/volumes/radarr/data:/data

networks:
  arr-stack:
    name: arr-stack
    external: true
