services:
    n8n:
      image: ghcr.io/n8n-io/n8n:2.39.2
      container_name: n8n
        
      restart: unless-stopped
      pull_policy: weekly

      ports:
        - 5678:5678

      volumes:
        - ~/volumes/n8n:/home/node/.n8n
        - ~/volumes/booklore/read_later:/home/node/.n8n-files/read_later:rw

      env_file: .env
      
    n8n-cache:
      image: redis:8.10-alpine
      container_name: n8n-cache

      restart: unless-stopped
      
      ports:
        - 5679:6379

      volumes:
        - redis_data:/data

volumes:
  redis_data:
