services:
    ngrok:
      image: ngrok/ngrok:3.39.11-alpine
      container_name: ngrok

      restart: unless-stopped

      env_file:
        - .env

      environment:
        NGROK_CONFIG: /etc/ngrok.yml

      command: ["start", "--all"]

      volumes:
        - ./ngrok.yml:/etc/ngrok.yml:ro

      ports:
        - 127.0.0.1:4040:4040

      depends_on:
        - n8n
