# metapac's config.toml file (like this one) should be placed in the following location
# dependent on the operating system as specified in the `dirs` crate:
# | Platform | Value                                                 | Example                                                      |
# | -------- | ----------------------------------------------------- | ------------------------------------------------------------ |
# | Linux    | $XDG_CONFIG_HOME or $HOME/.config/metapac/config.toml | /home/alice/.config/metapac/config.toml                      |
# | macOS    | $HOME/Library/Application Support/metapac/config.toml | /Users/Alice/Library/Application Support/metapac/config.toml |
# | Windows  | {FOLDERID_RoamingAppData}\metapac\config.toml         | C:\Users\Alice\AppData\Roaming\metapac\config.toml           |

# If this is `false` then the enabled backends will be found by using the value of
# the `enabled_backends` config.
# If this is `true` then the enabled backends will be found by using the
# [hostname_enabled_backends] config table.
#
# See the README.md or run `metapac backends` for the list of backend names.
# Default: false
hostname_enabled_backends_enabled = true

# Backends to enable. Subject to `hostname_enabled_backends_enabled`.
# Default: []
# enabled_backends = ["arch", "cargo"]

# If this is `false` all toml files recursively found in the groups folder
# will be used as group files.
# If this is `true` then the [hostname_groups] config table will be used to
# decide which group files to use per hostname.
# Default: false
hostname_groups_enabled = true

# Backends to enable per hostname. Subject to `hostname_enabled_backends_enabled`.
# Default: None
[hostname_enabled_backends]
Haseebs-Manjaro-SL3 = ["arch", "cargo", "npm"]
"Mac.lan" = ["brew", "cargo"]

# Which group files will be used per hostname. Subject to `hostname_groups_enabled`.
# Relative paths are relative to the groups folder.
# Default: None
[hostname_groups]
Haseebs-Manjaro-SL3 = ["default", "personal"]
"Mac.lan" = ["default", "work"]

[arch]
# Since pacman, pamac, paru, pikaur and yay all operate on the same package database
# they are mutually exclusive and so you must pick which one you want
# metapac to use.
# Must be one of: ["pacman", "pamac", "paru", "pikaur", "yay"]
# Default: "pacman"
package_manager = "pacman"

[brew]
# If this is `true` then brew packages default to using the `--quarantine`
# option.
# If this is `false` then brew packages default to using the `--no-quarantine`
# option.
# Default: true
quarantine = true

[cargo]
# Whether to default to installing cargo packages with the `--locked` option.
# Default: false
locked = false

[flatpak]
# If this is `true` then flatpak packages default to using the `--system`
# option.
# If this is `false` then flatpak packages default to using the `--user`
# option.
# Default: true
systemwide = false

[vscode]
# Since VSCode and VSCodium both operate on the same package database
# they are mutually exclusive and so you must pick which one you want
# metapac to use.
# Must be one of: ["code", "codium"]
# Default: "code"
variant = "codium"
