services:
  reitti:
    image: dedicatedcode/reitti:5.3.1
    container_name: reitti
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGIS_HOST: postgres
      POSTGIS_PORT: 5432
      POSTGIS_DB: reitti
      POSTGIS_USER: reitti
      POSTGIS_PASSWORD: ${REITTI_DB_PASSWORD}
      REDIS_HOST: reitti_redis
      REDIS_PORT: 6379
    ports:
      - "8082:8080"
    volumes:
      - ~/volumes/reitti/storage:/data
    depends_on:
      reitti_redis:
        condition: service_healthy

  reitti_redis:
    image: redis:8.10.1
    container_name: reitti_redis
    restart: unless-stopped
    volumes:
      - ~/volumes/reitti/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
